server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JxJxJxMxNxS/springCloudConfigFiles
          basedir: target/config
security:
  user:
    name: jxjxjxmxnxs
    password: 214332Jose
management:
  security:
    enabled: false